/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SplashScreen.java
 *
 * Created on 12/12/2009, 01:34:49 م
 */

package com.asc.presentation;

import java.awt.Color;
import java.io.IOException;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JWindow;
import javax.swing.UIManager;

/**
 *
 * @author ASC 0
 */
public class SplashScreen extends JWindow {
 ResourceBundle rb =
                    ResourceBundle.getBundle("configuration/bundle", Locale.getDefault());    /** Creates new form SplashScreen */
    public SplashScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><font color='#192874' size='8' >" + rb.getString("welcome") + "</font></html>");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asc/resources/lastTestLastTest.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws IOException, ClassNotFoundException {
        try {
            // UIManager.setLookAndFeel(QuaquaManager.getLookAndFeelClassName());
            for (UIManager.LookAndFeelInfo laf : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(laf.getName())) {
                    UIManager.setLookAndFeel(laf.getClassName());
                    // UIManager.put("nimbusBase",  new Color(8, 2, 56));
                    //UIManager.put("text", new Color(0, 81, 0));
                    UIManager.put("control", Color.white);

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        SplashScreen sp = new SplashScreen();
        com.sun.awt.AWTUtilities.setWindowOpaque(sp, false);
        sp.setVisible(true);
        try{
            Thread.sleep(2000);
        }catch(Exception ex)
        {

        }
        sp.dispose();
//        MainFrame mf = new MainFrame();
//        mf.setVisible(true);
        ManufacturerLibraryFrame mfLib = new ManufacturerLibraryFrame();
        mfLib.setVisible(true);

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
