package com.asc.bean;
// Generated Dec 17, 2009 10:48:19 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Key generated by hbm2java
 */
public class Key  implements java.io.Serializable {


     private Integer id;
     private byte[] privateK;
     private byte[] publicK;
     private String description;
     private Date date;
     private String tag;
     private String alias;

    public Key() {
    }

    public Key(byte[] privateK, byte[] publicK, String description, Date date, String tag, String alias) {
       this.privateK = privateK;
       this.publicK = publicK;
       this.description = description;
       this.date = date;
       this.tag = tag;
       this.alias = alias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public byte[] getPrivateK() {
        return this.privateK;
    }
    
    public void setPrivateK(byte[] privateK) {
        this.privateK = privateK;
    }
    public byte[] getPublicK() {
        return this.publicK;
    }
    
    public void setPublicK(byte[] publicK) {
        this.publicK = publicK;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }




}


